# .github/workflows/cicd.yml

name: CI/CD Pipeline - Build, Push, and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: Set image name to lowercase
        run: echo "IMAGE_NAME=$(echo ghcr.io/${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

  # --- 아래 deploy 작업이 새로 추가되었습니다 ---
  deploy:
    # build-and-push 작업이 성공해야만 실행됨
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to OCI VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # GHCR에 로그인
            docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.PAT }}
            
            # 기존 컨테이너가 있으면 중지하고 삭제 (오류 무시)
            docker stop ner-api-server || true
            docker rm ner-api-server || true
            
            # 최신 이미지 pull
            export IMAGE_NAME=$(echo ghcr.io/${{ github.repository }} | tr '[:upper:]' '[:lower:]')
            docker pull ${IMAGE_NAME}:latest
            
            # 새 컨테이너 실행
            docker run -d \
              --name ner-api-server \
              -p 8000:8000 \
              -v /home/opc/ner_project/Wallet_QJ5STCTDZPUJ2AMT:/app/adw_wallet:ro \
              ${IMAGE_NAME}:latest

                    # --- 아래 단계를 deploy 작업의 마지막에 추가 ---
      - name: Create and push tag
        run: |
          # 날짜 기반으로 태그 이름 생성 (예: model-20250722-1457)
          TAG_NAME="model-$(date +%Y%m%d-%H%M)"
          echo "Creating tag ${TAG_NAME}"

          # Git 사용자 정보 설정
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # 태그 생성 및 푸시
          git tag ${TAG_NAME}
          git push origin ${TAG_NAME}
