# .github/workflows/cicd.yml

name: CI/CD Pipeline - Build, Push, and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: Set image name to lowercase
        run: echo "IMAGE_NAME=$(echo ghcr.io/${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      # 1단계: 로그인하고 오래 걸리는 이미지를 pull 받기
      - name: Pull latest image on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          timeout: 30m  # 이미지 pull을 위해 30분 대기
          script: |
            /usr/bin/docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.PAT }}
            export IMAGE_NAME=$(echo ghcr.io/${{ github.repository }} | tr '[:upper:]' '[:lower:]')
            /usr/bin/docker pull ${IMAGE_NAME}:latest

      # 2단계: 기존 컨테이너를 중지하고 새 컨테이너 실행
      - name: Stop, Remove, and Run new container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            /usr/bin/docker stop ner-api-server || true
            /usr/bin/docker rm ner-api-server || true
            export IMAGE_NAME=$(echo ghcr.io/${{ github.repository }} | tr '[:upper:]' '[:lower:]')
            /usr/bin/docker run -d \
              --name ner-api-server \
              -p 8000:8000 \
              -v /home/opc/ner_project/Wallet_QJ5STCTDZPUJ2AMT:/app/adw_wallet:ro \
              ${IMAGE_NAME}:latest
